---
- name: lab09s4p2
  hosts: n01465744-c-vm2.canadacentral.cloudapp.azure.com
  tasks:
    - name: Install {{ packages }} if there is sufficient storage
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/" and item.size_available > 400000
...