---
- name: lab09s3p3
  hosts: linux
  tasks:
    - name: Add text to /tmp/conditional
      ansible.builtin.blockinfile:
        path: /tmp/conditional
        insertafter: EOF
        state: present
        block:
          - "This is my CentOS VM"
      when:
        - ansible_distribution_version == "8.2"
        - ansible_kernel == "4.18.0-193.el8.x86_64"
...