---
- name: lab09s1p1
  hosts: n01465744-c-vm1.canadacentral.cloudapp.azure.com
  tasks:
    - name: Install bind and evolution
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest
      register: install_result
    - name: Display install results
      debug:
        var: install_result
...