---
- name: lab09s3p1
  hosts: n01465744-c-vm1.canadacentral.cloudapp.azure.com
  vars:
    packages: nmap
  tasks:
    - name: Install "{{ packages }}" packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest
      when: packages is defined
...